import type { Metadata } from "next";
import "./globals.css";
import { Toolbar } from "../components/Toolbar";
import { Footer } from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-off-white"
        
      >
        <Toolbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
